CREATE TABLE 'contagem_pontos' ('titulacao' TEXT,'prova' TEXT,'referencia' TEXT,'calculo' TEXT,'nota_maxima' INTEGER,'peso' TEXT,'nota_maxima_ponderada' INTEGER,'nota_corte_ponderada' INTEGER);
INSERT INTO 'contagem_pontos' ('titulacao','prova','referencia','calculo','nota_maxima','peso','nota_maxima_ponderada','nota_corte_ponderada') VALUES 
 ('10%','P1','0,1-P1','100* Nº acertos / 20','100','0,2','20','8'), 
 ('10%','P2','0,1-P2','((Nº acertos eixo temático 1)* peso eixo temático 1) + ((Nº acertos eixo temático 2)* peso eixo temático 2) + ((Nº acertos eixo temático 3)* peso eixo temático 3) + ((Nº acertos eixo temático 4)* peso eixo temático 4) + ((Nº acertos eixo temático 5)* peso eixo temático 5)','100','0,5','50','20'), 
 ('10%','P3','0,1-P3','Nota','100','0,2','20',null), 
 ('10%','P4','0,1-P4','10* (Total de pontos)','100','0,1','10',null), 
 ('5%','P1','0,05-P1','100* Nº acertos / 20','100','0,25','25','10'), 
 ('5%','P2','0,05-P2','((Nº acertos eixo temático 1)* peso eixo temático 1) + ((Nº acertos eixo temático 2)* peso eixo temático 2) + ((Nº acertos eixo temático 3)* peso eixo temático 3) + ((Nº acertos eixo temático 4)* peso eixo temático 4) + ((Nº acertos eixo temático 5)* peso eixo temático 5)','100','0,5','50','20'), 
 ('5%','P3','0,05-P3','Nota','100','0,2','20',null), 
 ('5%','P4','0,05-P4','10* (Total de pontos)','100','0,05','5',null), 
 ('0%','P1','0-P1','100* Nº acertos / 20','100','0,25','25','10'), 
 ('0%','P2','0-P2','((Nº acertos eixo temático 1)* peso eixo temático 1) + ((Nº acertos eixo temático 2)* peso eixo temático 2) + ((Nº acertos eixo temático 3)* peso eixo temático 3) + ((Nº acertos eixo temático 4)* peso eixo temático 4) + ((Nº acertos eixo temático 5)* peso eixo temático 5)','100','0,55','55','22'), 
 ('0%','P3','0-P3','Nota','100','0,2','20',null)
 ;

CREATE TABLE 'cargo_x_titulacao' ('bloco' TEXT,'codigo' TEXT,'nome' TEXT,'titulacao' TEXT);
INSERT INTO 'cargo_x_titulacao' ('bloco','codigo','nome','titulacao') VALUES 
 ('Bloco 2','B2-08-A','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Analista em Tecnologia da Informação (ATI), Especialidade: Tecnologia da Informação','10%'), 
 ('Bloco 2','B2-08-C','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Especialistas em Políticas Públicas e Gestão Governamental (EPPGG), Especialidade: Qualquer área de conhecimento','10%'), 
 ('Bloco 2','B2-08-B','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Analista Técnico de Políticas Sociais : ATPS, Especialidade: Tecnologia da Informação','10%'), 
 ('Bloco 2','B2-07-B','Ministério da Ciência, Tecnologia e Inovação : MCTI, Cargo: Analista em Ciência e Tecnologia, Especialidade: Tecnologia da Informação','10%'), 
 ('Bloco 2','B2-07-A','Ministério da Ciência, Tecnologia e Inovação : MCTI, Cargo: Analista em Ciência e Tecnologia, Especialidade: Estatística e Ciência de Dados','10%'), 
 ('Bloco 2','B2-05-A','Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira : INEP, Cargo: Pesquisador-Tecnologista em Informações e Avaliações Educacionais, Especialidade: Qualquer área de conhecimento','10%'), 
 ('Bloco 2','B2-02-A','Fundação Nacional dos Povos Indígenas : FUNAI, Cargo: Especialista em Indigenismo, Especialidade: Estatística','10%'), 
 ('Bloco 2','B2-09-A','Ministério da Saúde : MS, Cargo: Tecnologista, Especialidade: Tecnologia da Informação','10%'), 
 ('Bloco 2','B2-10-A','Superintendência Nacional de Previdência Complementar : PREVIC, Cargo: Analista administrativo, Especialidade: Tecnologia da Informação','5%'), 
 ('Bloco 2','B2-01-A','Advocacia Geral da União : AGU, Cargo: Cargo: Estatístico, Especialidade: Estatística.','5%'), 
 ('Bloco 2','B2-03-A','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Analista de Planejamento, Gestão e Infraestrutura em Informações Geográficas e Estatísticas, Especialidade: Desenvolvimento de Tecnologia de Informação','0%'), 
 ('Bloco 2','B2-03-C','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Analista de Planejamento, Gestão e Infraestrutura em Informações Geográficas e Estatísticas, Especialidade: Redes e telecomunicações7','0%'), 
 ('Bloco 2','B2-03-B','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Analista de Planejamento, Gestão e Infraestrutura em Informações Geográficas e Estatísticas, Especialidade: Infraestrutura e suporte de Tecnologia da Informação','0%'), 
 ('Bloco 2','B2-03-G','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Métodos quantitativos','0%'), 
 ('Bloco 2','B2-03-E','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Ciência de dados','0%'), 
 ('Bloco 2','B2-03-H','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Webdesigner e produção gráfica ','0%'), 
 ('Bloco 2','B2-03-F','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Estatística','0%'), 
 ('Bloco 2','B2-03-D','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Pesquisador em Informações Geográficas e Estatísticas, Especialidade: Estatística','0%'), 
 ('Bloco 2','B2-06-A','Ministério da Agricultura e Pecuária : MAPA, Cargo: Analista em Ciência e Tecnologia, Especialidade: Tecnologia da Informação ','0%'), 
 ('Bloco 2','B2-04-A','Instituto Nacional de Colonização e Reforma Agrária : INCRA, Cargo: Analista administrativo, Especialidade: Tecnologia da Informação','0%'), 
 ('Bloco 2','B2-08-D','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Estatístico, Especialidade: Estatística.','0%'), 
 ('Bloco 7','B7-02-A','Fundação Nacional dos Povos Indígenas - FUNAI, Cargo: Especialista em Indigenismo, Especialidade: Administração','10%'), 
 ('Bloco 7','B7-02-B','Fundação Nacional dos Povos Indígenas : FUNAI, Cargo: Especialista em Indigenismo, Especialidade: Arquivologia 20','10%'), 
 ('Bloco 7','B7-02-C','Fundação Nacional dos Povos Indígenas : FUNAI, Cargo: Especialista em Indigenismo, Especialidade: Biblioteconomia','10%'), 
 ('Bloco 7','B7-02-D','Fundação Nacional dos Povos Indígenas - FUNAI, Cargo: Especialista em Indigenismo, Especialidade: Comunicação Social','10%'), 
 ('Bloco 7','B7-02-E','Fundação Nacional dos Povos Indígenas : FUNAI, Cargo: Especialista em Indigenismo, Especialidade: Contabilidade','10%'), 
 ('Bloco 7','B7-05-A','Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira : INEP, Cargo: Pesquisador-Tecnologista em Informações e Avaliações Educacionais, Especialidade: Qualquer área de conhecimento','10%'), 
 ('Bloco 7','B7-09-E','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Especialistas em Políticas Públicas e Gestão Governamental (EPPGG), Especialidade: Qualquer área de conhecimento','10%'), 
 ('Bloco 7','B7-07-E','Ministério da Ciência, Tecnologia e Inovação : MCTI, Cargo: Analista em Ciência e Tecnologia, Especialidade: Qualquer área de conhecimento','10%'), 
 ('Bloco 7','B7-07-B','Ministério da Ciência, Tecnologia e Inovação : MCTI, Cargo: Analista em Ciência e Tecnologia, Especialidade: Biblioteconomia','10%'), 
 ('Bloco 7','B7-07-A','Ministério da Ciência, Tecnologia e Inovação : MCTI, Cargo: Analista em Ciência e Tecnologia, Especialidade: Arquivologia','10%'), 
 ('Bloco 7','B7-07-D','Ministério da Ciência, Tecnologia e Inovação : MCTI, Cargo: Analista em Ciência e Tecnologia, Especialidade: Contabilidade','10%'), 
 ('Bloco 7','B7-07-C','Ministério da Ciência, Tecnologia e Inovação : MCTI, Cargo: Analista em Ciência e Tecnologia, Especialidade: Comunicação Social','10%'), 
 ('Bloco 7','B7-11-A','Ministério da Saúde : MS, Cargo: Tecnologista, Especialidade: Administração, Contabilidade, Economia ou Estatística.','10%'), 
 ('Bloco 7','B7-01-B','Advocacia Geral da União : AGU, Cargo: Analista Técnico Administrativo, Especialidade: Qualquer área de conhecimento','5%'), 
 ('Bloco 7','B7-01-A','Advocacia Geral da União : AGU, Cargo: Administrador, Especialidade: Administração','5%'), 
 ('Bloco 7','B7-01-E','Advocacia Geral da União : AGU, Cargo: Técnico em Comunicação Social, Especialidade: Comunicação Social','5%'), 
 ('Bloco 7','B7-14-A','Superintendência Nacional de Previdência Complementar : PREVIC, Cargo: Analista Administrativo, Especialidade: Qualquer área de conhecimento','5%'), 
 ('Bloco 7','B7-01-D','Advocacia Geral da União : AGU, Cargo: Contador, Especialidade: Contabilidade','5%'), 
 ('Bloco 7','B7-01-C','Advocacia Geral da União : AGU, Cargo: Arquivista, Especialidade: Arquivologia ','5%'), 
 ('Bloco 7','B7-04-C','Instituto Nacional de Colonização e Reforma Agrária : INCRA, Cargo: Analista Administrativo, Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 7','B7-04-B','Instituto Nacional de Colonização e Reforma Agrária : INCRA, Cargo: Analista Administrativo, Especialidade: Contabilidade','0%'), 
 ('Bloco 7','B7-04-A','Instituto Nacional de Colonização e Reforma Agrária : INCRA, Cargo: Analista Administrativo (Técnico em Comunicação), Especialidade: Comunicação Social','0%'), 
 ('Bloco 7','B7-04-D','Instituto Nacional de Colonização e Reforma Agrária : INCRA, Cargo: Analista em Reforma e Desenvolvimento Agrário, Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 7','B7-09-A','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Analista Técnico Administrativo, Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 7','B7-09-B','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Arquivista, Especialidade: Arquivologia','0%'), 
 ('Bloco 7','B7-09-C','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Bibliotecário, Especialidade: Biblioteconomia','0%'), 
 ('Bloco 7','B7-09-F','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Técnico em Comunicação Social, Especialidade: Comunicação Social','0%'), 
 ('Bloco 7','B7-09-D','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Contador, Especialidade: Contabilidade','0%'), 
 ('Bloco 7','B7-12-A','Ministério do Desenvolvimento, Indústria, Comércio e Serviços : MDIC, Cargo: Analista Técnico Administrativo, Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 7','B7-13-A','Ministério do Planejamento e Orçamento : MPO, Cargo: Analista Técnico Administrativo, Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 7','B7-10-A','Ministério da Justiça e Segurança Pública : MJSP, Cargo: Analista Técnico Administrativo, Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 7','B7-08-A','Ministério da Cultura : MinC, Cargo: Analista Técnico Administrativo, Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 7','B7-03-A','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Analista de Planejamento, Gestão e Infraestrutura em Informações Geográficas e Estatísticas, Especialidade: Ciências contábeis','0%'), 
 ('Bloco 7','B7-03-D','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Analista de Planejamento, Gestão e Infraestrutura em Informações Geográficas e Estatísticas, Especialidade: Planejamento, Orçamento e gestão administrativa, auditoria e corregedoria 21','0%'), 
 ('Bloco 7','B7-03-C','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Analista de Planejamento, Gestão e Infraestrutura em Informações Geográficas e Estatísticas, Especialidade: Letras (português-inglês)','0%'), 
 ('Bloco 7','B7-03-B','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Analista de Planejamento, Gestão e Infraestrutura em Informações Geográficas e Estatísticas, Especialidade: Educação corporativa e administração escolar','0%'), 
 ('Bloco 7','B7-03-I','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Planejamento e gestão técnica administrativa','0%'), 
 ('Bloco 7','B7-03-E','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Arquivologia','0%'), 
 ('Bloco 7','B7-03-F','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Biblioteconomia','0%'), 
 ('Bloco 7','B7-03-G','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Comunicação social','0%'), 
 ('Bloco 7','B7-03-H','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: História','0%'), 
 ('Bloco 7','B7-03-J','Instituto Brasileiro de Geografia e Estatística : IBGE, Cargo: Tecnologista em Informações Geográficas e Estatísticas, Especialidade: Produção audiovisual e publicidade e propaganda','0%'), 
 ('Bloco 7','B7-06-A','Ministério da Agricultura e Pecuária : MAPA, Cargo: Analista em Ciência e Tecnologia, Especialidade: Qualquer área de conhecimento.','0%'), 
 ('Bloco 4','B4-02-A','Fundação Nacional dos Povos Indígenas : FUNAI, Cargo: Especialista em Indigenismo, Especialidade: Psicologia','10%'), 
 ('Bloco 4','B4-03-B','Ministério da Gestão e da Inovação em Serviços Públicos : Cargo: MGI, Especialistas em Políticas Públicas e Gestão Governamental (EPPGG), Especialidade: Qualquer área de conhecimento.','10%'), 
 ('Bloco 4','B4-01-A','Advocacia Geral da União : AGU, Cargo: Médico, Especialidade: Medicina','5%'), 
 ('Bloco 4','B4-01-B','Advocacia Geral da União : AGU, Cargo: Psicólogo, Especialidade: Psicologia','5%'), 
 ('Bloco 4','B4-04-A','Ministério do Trabalho e Emprego : MTE, Cargo: Auditor-Fiscal do Trabalho (AFT), Especialidade: Qualquer área de conhecimento','0%'), 
 ('Bloco 4','B4-03-C','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Médico, Especialidade: Medicina','0%'), 
 ('Bloco 4','B4-03-D','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Médico, Especialidade: Medicina : psiquiatria','0%'), 
 ('Bloco 4','B4-03-E','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Psicólogo, Especialidade: Psicologia','0%'), 
 ('Bloco 4','B4-03-A','Ministério da Gestão e da Inovação em Serviços Públicos : MGI, Cargo: Analista Técnico de Políticas Sociais : ATPS, Especialidade: Qualquer área de conhecimento.','0%')
 ;

CREATE TABLE 'pesos_eixos' ('codigo' TEXT,'eixo1' INTEGER,'eixo2' INTEGER,'eixo3' INTEGER,'eixo4' INTEGER,'eixo5' INTEGER);
INSERT INTO 'pesos_eixos' ('codigo','eixo1','eixo2','eixo3','eixo4','eixo5') VALUES 
 ('B2-01-A','1','2','1','1','5'), 
 ('B2-02-A','2','3','2','1','2'), 
 ('B2-03-A','1','1','2','5','1'), 
 ('B2-03-B','1','1','5','1','2'), 
 ('B2-03-C','1','1','3','3','2'), 
 ('B2-03-D','1','2','1','1','5'), 
 ('B2-03-E','1','1','2','2','4'), 
 ('B2-03-F','1','2','1','1','5'), 
 ('B2-03-G','1','2','1','1','5'), 
 ('B2-03-H','2','2','2','2','2'), 
 ('B2-04-A','1','1','3','3','2'), 
 ('B2-05-A','1','2','1','1','5'), 
 ('B2-06-A','1','1','3','3','2'), 
 ('B2-07-A','2','2','1','1','4'), 
 ('B2-07-B','2','3','3','1','1'), 
 ('B2-08-A','1','1','3','3','2'), 
 ('B2-08-B','2','3','1','1','1'), 
 ('B2-08-C','4','3','1','1','1'), 
 ('B2-08-D','2','1','1','1','5'), 
 ('B2-09-A','1','1','3','3','2'), 
 ('B2-10-A','1','1','3','3','2'), 
 ('B7-02-A','2','2','2','2','2'), 
 ('B7-02-B','2','2','1','1','4'), 
 ('B7-02-C','2','2','1','1','4'), 
 ('B7-02-D','2','2','1','1','4'), 
 ('B7-02-E','2','1','3','3','1'), 
 ('B7-05-A','2','3','1','3','1'), 
 ('B7-09-E','3','3','2','1','1'), 
 ('B7-07-E','3','2','1','3','1'), 
 ('B7-07-B','2','2','1','1','4'), 
 ('B7-07-A','2','2','1','1','4'), 
 ('B7-07-D','2','2','1','4','1'), 
 ('B7-07-C','2','1','1','2','4'), 
 ('B7-11-A','1','2','2','4','1'), 
 ('B7-01-B','2','3','2','2','1'), 
 ('B7-01-A','3','3','1','2','1'), 
 ('B7-01-E','1','2','1','1','5'), 
 ('B7-14-A','3','2','1','3','1'), 
 ('B7-01-D','1','2','1','5','1'), 
 ('B7-01-C','1','3','1','1','4'), 
 ('B7-04-C','3','2','2','2','1'), 
 ('B7-04-B','1','1','2','5','1'), 
 ('B7-04-A','2','1','1','1','5'), 
 ('B7-04-D','2','2','1','3','2'), 
 ('B7-09-A','2','2','2','2','2'), 
 ('B7-09-B','2','1','1','1','5'), 
 ('B7-09-C','2','1','1','1','5'), 
 ('B7-09-F','2','1','1','1','5'), 
 ('B7-09-D','2','1','1','5','1'), 
 ('B7-12-A','2','2','2','2','2'), 
 ('B7-13-A','2','2','2','2','2'), 
 ('B7-10-A','1','2','3','3','1'), 
 ('B7-08-A','4','2','1','1','2'), 
 ('B7-03-A','1','2','2','4','1'), 
 ('B7-03-D','1','2','2','4','1'), 
 ('B7-03-C','4','1','1','1','3'), 
 ('B7-03-B','4','1','2','1','2'), 
 ('B7-03-I','2','2','2','2','2'), 
 ('B7-03-E','2','2','1','1','4'), 
 ('B7-03-F','2','2','1','1','4'), 
 ('B7-03-G','2','1','2','1','4'), 
 ('B7-03-H','2','2','1','1','4'), 
 ('B7-03-J','3','1','2','1','3'), 
 ('B7-06-A','2','2','2','2','2'), 
 ('B4-01-A','1','1','2','5','1'), 
 ('B4-01-B','1','1','5','2','1'), 
 ('B4-02-A','2','3','3','1','1'), 
 ('B4-03-A','4','3','1','1','1'), 
 ('B4-03-B','4','3','1','1','1'), 
 ('B4-03-C','1','1','1','5','2'), 
 ('B4-03-D','1','1','1','5','2'), 
 ('B4-03-E','1','1','5','1','2'), 
 ('B4-04-A','1','1','2','3','3')
 ;